//! Windows SAPI Emergency Local Fallback TTS provider.
//! Operates completely offline with 0 VRAM and 0 GPU overhead.
//! Only utilized when all cloud providers are unreachable or exhausted.

use async_trait::async_trait;
use base64::Engine;
use std::process::Command;
use tracing::{debug, warn};

use crate::provider::traits::{
    AudioData, EstimatedCost, ProviderError, TTSCapabilities, TTSProvider,
    VoiceLanguage,
};

pub struct LocalSapiTTSProvider {
    capabilities: TTSCapabilities,
}

impl LocalSapiTTSProvider {
    pub fn new() -> Self {
        Self {
            capabilities: TTSCapabilities {
                streaming: false,
                supported_languages: vec![VoiceLanguage::English],
                emotional_styles: false,
                speed_control: true,
                pitch_control: false,
                typical_first_byte_ms: 300,
                cost_per_char_usd: 0.0,
            },
        }
    }

    fn decode_wav_file(path: &std::path::Path) -> Result<AudioData, ProviderError> {
        let bytes = std::fs::read(path).map_err(|e| {
            ProviderError::SynthesisFailed(format!("Failed to read SAPI wav output: {}", e))
        })?;

        if bytes.len() < 44 || &bytes[0..4] != b"RIFF" {
            return Err(ProviderError::SynthesisFailed(
                "Invalid WAV generated by SAPI".into(),
            ));
        }

        let channels = u16::from_le_bytes([bytes[22], bytes[23]]);
        let sample_rate = u32::from_le_bytes([bytes[24], bytes[25], bytes[26], bytes[27]]);
        let pcm_bytes = bytes[44..].to_vec();

        Ok(AudioData::new(pcm_bytes, sample_rate, channels))
    }
}

impl Default for LocalSapiTTSProvider {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl TTSProvider for LocalSapiTTSProvider {
    fn id(&self) -> &'static str {
        "local-sapi-tts"
    }

    fn name(&self) -> &'static str {
        "Windows SAPI Emergency Local Fallback"
    }

    fn capabilities(&self) -> &TTSCapabilities {
        &self.capabilities
    }

    async fn synthesize(
        &self,
        text: &str,
        _language: Option<VoiceLanguage>,
    ) -> Result<AudioData, ProviderError> {
        let temp_dir = std::env::temp_dir();
        let file_name = format!("voxy_sapi_{}_{}.wav", std::process::id(), uuid::Uuid::new_v4());
        let wav_path = temp_dir.join(file_name);
        let wav_path_str = wav_path.to_string_lossy().to_string();

        let b64_text = base64::engine::general_purpose::STANDARD.encode(text.as_bytes());
        let b64_path = base64::engine::general_purpose::STANDARD.encode(wav_path_str.as_bytes());

        debug!(provider = self.id(), "Rendering speech via Windows SAPI fallback");

        let script = format!(
            "Add-Type -AssemblyName System.Speech; \
             $p = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('{}')); \
             $t = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('{}')); \
             $synth = New-Object System.Speech.Synthesis.SpeechSynthesizer; \
             $synth.SetOutputToWaveFile($p); \
             $synth.Speak($t); \
             $synth.Dispose();",
            b64_path, b64_text
        );

        let output = tokio::task::spawn_blocking(move || {
            Command::new("powershell")
                .args(["-NoProfile", "-NonInteractive", "-Command", &script])
                .output()
        })
        .await
        .map_err(|e| ProviderError::SynthesisFailed(e.to_string()))?
        .map_err(|e| ProviderError::SynthesisFailed(format!("Failed to execute powershell: {}", e)))?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            warn!(stderr = %stderr, "SAPI synthesis command failed");
            let _ = std::fs::remove_file(&wav_path);
            return Err(ProviderError::SynthesisFailed(format!(
                "SAPI execution error: {}",
                stderr
            )));
        }

        let audio = Self::decode_wav_file(&wav_path);
        let _ = std::fs::remove_file(&wav_path);
        audio
    }

    fn estimate_cost(&self, _character_count: usize) -> EstimatedCost {
        EstimatedCost {
            amount_usd: 0.0,
            currency: "USD".into(),
            estimated_cost_usd: 0.0,
            billable_units: 0.0,
            unit_type: "characters".into(),
        }
    }
}
